### ISSUE TITLE
[bug] Unknown CFFI type: :STRUCT

### ISSUE THREAD

**Issue by JuanitoFatas** [tkych/quicksearch#1]
OS: OSX 10.6.8
SBCL: 1.1.7 (with thread)
ASDF: "2.33"

Hi! I follow the procedure and install quicksearch then try out the first example:

``` cl
(qs:? "supercalifragilisticexpialidocious")

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "bitbucket-search" RUNNING {1003F8B463}>:
  Unknown CFFI type: :STRUCT.
```

Then SBCL is hanging (not responding).

**Comment by tkych** [comment]
Thanks bug report.
I'm trying to fix it.

**Comment by tkych** [comment]
1. The following might be help to solve this problem.
   http://comments.gmane.org/gmane.lisp.quicklisp/469
2. I modified codes for non-threading CL implementations.
   By `(qs:config :threading-p nil)`, quicksearch does not use threads for searching.

**Comment by JuanitoFatas** [comment]
my cffi is 0.10.7, the latest is 0.11.2, I am trying to update CFFI.

**Comment by JuanitoFatas** [comment]
OK. When I update CFFI to 0.11.2, this issue is resolved.
